# docker-compose.yml
services:
  web:
    # ... (no changes needed here from previous example)
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "db:3306", "--timeout=60", "--", "python", "app.py"]
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # --- IMPORTANT CHANGE HERE ---
      - ./data:/docker-entrypoint-initdb.d # Mount the entire data directory
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data: